### ISSUE TITLE
Support for extracting cursors from nested requests

### ISSUE THREAD

**Issue by StephenFlavin** [restfb/restfb#1046]
I was recently working with the [instagram business discovery api](https://developers.facebook.com/docs/instagram-api/guides/business-discovery/) and had some trouble extracting everything I needed.

The response is basically an IgUser within a business discovery json object.

For my use case I'm mainly interested in the `/media` edge for IgUsers so to start I wrote a simple class:

```
public class BusinessDiscoveryResponse extends FacebookType {
    private static final long serialVersionUID = 1L;

    @Facebook("business_discovery")
    private IgUser igUser;

    public IgUser getIgUser() {
        return igUser;
    }
}
```
This did the trick however, since [IgUser::getMedia](https://github.com/restfb/restfb/blob/master/src/main/lombok/com/restfb/types/instagram/IgUser.java#L133) only contains the `List<IgMedia>` I had to write additional parsing to extract the cursor.
```
private static class NestedMedia{
    @Facebook("media")
    private Page page;
    private static class Page{
        @Facebook
        private Paging paging;
        private static class Paging {
            @Facebook
            private Cursors cursors;
            private static class Cursors {
                @Facebook
                private String after;
            }
        }
    }
}
```
Is there something I've missed here when it comes to nested requests?

I had originally looked into extending IgUser and adding a `Page<IgMedia>` which parsed out the cursors and just contained methods for `getCursors()` and `getMedia()` but there's no simple way to do that without making an entirely new IgUser that extends FacebookType and doing all the parsing from scratch.

**Comment by nbartels** [comment]
Yes you are right, this is a missing feature in restfb. ATM it is not possible to return a `Connection` object. This would solve the problem. Imho most developers use additional calls to fetch this paged lists/nested objects. 

I let this issue open to track it, and hopefully we find a great solution for the problem.

**Comment by StephenFlavin** [comment]
Yeah I'd avoid it if I could but it's the only way to use the business discovery api unfortunately.
Anyway thanks for the response, I had a horrible feeling I was just missing something obvious.

**Comment by nbartels** [comment]
I'd like to link this issue to #687 - It's a similar issue and the solution ist the same.
We are currently working on adding the `Connection` object as mapping type. This means you can add a `Connection` instead of a list or a custom objects (like `Comments`) to access all the necessary stuff and even iterate over the complete list. This means in a Post object is a connection that leads to all comments. The first page of them is part of the Post and then you can iterate over all pages. This may lead to other problems, but we like to share the change and you can already test it. With the coming releases we change our type objects to improve the further.
