### ISSUE TITLE
ETag support

### ISSUE THREAD

**Issue by revetkn** [restfb/restfb#106]
See

Request: https://groups.google.com/forum/#!topic/restfb/JFs6YyVl1b0
FB docs: https://developers.facebook.com/blog/post/627/
PHP implementation: https://github.com/facebook/facebook-php-sdk/pull/30

**Comment by nbartels** [comment]
In my opinion, only the ```GET```-calls should use etags, because I'm allowed to post the same data at the same resource several times and get every time a new response. So the caching approach cannot work. Besides from that ```POST``` responses are more or less small.

If I fetch data from FB, I use a specific call and perhaps the response has changed or not. And the "not case" is the interesting part where we can pull data from our cache. 

I suggest to implement the ```SoftHashMap``` where the value consists of 2 fields. The Etag and the response body. The key is only the checksummed URL. Perhaps even the String is enough, but unsure about that. 

As soon as some data is fetched from Facebook, the http method is checked and we look in the cache for the key. If something's found the etag from the value is used as ```if-none-match``` header field. Is the response code 304 we return the response body from cache, is it 200 we update the cache, otherwise we remove the cache entry completely. Perhaps something has been deleted, so we don't need the information.

The switch, @revetkn suggested, is important, but perhaps we provide an alternative ```WebRequestor``` implementation instead. Unsure about this, too.

**Comment by nbartels** [comment]
ETag support added. I added the SoftHashMap @revetkn mentioned above and got the OK from Dr. Kabutz to use it here. He made the note, that the soft references can lead to a performance issue if "overused".

**Comment by revetkn** [comment]
Using a new WebRequestor was a nice solution, so users can opt-in without us having to change the FacebookClient contract.  Also cool that Heinz Kabutz gave the OK to use his code!
