### ISSUE TITLE
RestFB removing blank spaces in posts

### ISSUE THREAD

**Issue by RowanBurns01** [restfb/restfb#1067]
Hi there,

I am trying to post a table in a Facebook group using white space as padding, however, when it posts, it either removes the white space or I can use zero-width-spaces but they do not take up as much space.

This is what I would like it to look like:

![temp](https://user-images.githubusercontent.com/54560359/77814885-1a25e180-711a-11ea-9229-fe4eba0721d7.JPG)

Yet it looks like this:

 Day 2 Leaderboard:
     ----------------------------------------------------------------------------------------------
     | District | Tribute            | Kills | Level | Health | Attack | Defence | Speed | Status |
     ----------------------------------------------------------------------------------------------
     | 14       | Justin Ford        | 2     | 2     | 163    | 22     | 22      | 5     | Alive  |
     | 1        | Will Perry         | 1     | 1     | 107    | 12     | 12      | 7     | Alive  |
     | 6        | Andrew Fitzpatrick | 1     | 1     | 100    | 8      | 8       | 6     | Fallen |
     | 23       | Daniel Buffa       | 1     | 1     | 101    | 7      | 7       | 3     | Alive  |
     | 25       | Jack Woods         | 1     | 1     | 90     | 10     | 10      | 2     | Fallen |
     ----------------------------------------------------------------------------------------------

Is there a work around to post tables with nice formatting? 
Any help would be appreciated.

Warm regards,
Rowan Burns

**Comment by RowanBurns01** [comment]
ahh, this has also removed the white spaces on posting haha, pretend like the top example has white space padding.

**Comment by nbartels** [comment]
The problem is the HTML presentation of your input. Neither RestFB nor Facebook itself remove any spaces, but HTML shows only one blank even if there is a bunch of them. 

I used your example and on Facebook it looks as you describe it:
![image](https://user-images.githubusercontent.com/1113969/77833517-3dfb1e80-713e-11ea-8a8e-982786594811.png)

Checking the HTML code it looks correct:
![image](https://user-images.githubusercontent.com/1113969/77833537-73077100-713e-11ea-9701-ff5f1905c8d0.png)

Without trying this, here is a possibility I would go for. Try to find a unicode character that is not reduced by HTML. The non-breaking space seems not to work, but maybe there is another one. Or convert your table into an image and post that image to Facebook. Not the best way, but so it looks like intended.
