### ISSUE TITLE
How to get all likes?

### ISSUE THREAD

**Issue by trooperos** [restfb/restfb#111]
I need to get al people who liked given post .
I see the post liked about 6500 people, but given the url https://graph.facebook.com/283635191812312/likes?limit=100&offset=1000
give no result.
I can get only first 1000 likers. Ive tried something like

jsonObject = facebookClient.fetchObject("283635191812312/likes?,Param.with("offset",1000)) and that didnt help.

**Comment by rgupta77** [comment]
When i use the following code

Connection<Likes> myFeed = facebookClient23.fetchConnection(pageId + "/likes", Likes.class, Parameter.with("fields", "data,limit(0)"));
the myFeed has all likes but there is no data, the data field is an empty array. Can you tell me how to get the data array for each like

**Comment by nbartels** [comment]
According to the [API description](https://developers.facebook.com/docs/graph-api/reference/page) the `likes` field of a `Page` contains the pages the page likes.

To get the likes count, the `fan_count` field should be requested. It seems there is no way to fetch every single user. Check the changes from 2.5 to 2.6 in the [changelog](https://developers.facebook.com/docs/apps/changelog#v2_6).

**Comment by rgupta77** [comment]
Is it possible to get the list of all the followers of a facebook page using restfb?

**Comment by nbartels** [comment]
If there is no way to fetch this information via Graph API, then there is no way to fetch it with RestFB.

**Comment by rgupta77** [comment]
Hi Norbert,
Just wanted to know the correct way to get the Likes of a page (meaning Pages Liked by a Page)

When i use the following code, I get the likes collection, but the data array is null.
`Connection<Likes> myLikesConn = client.fetchConnection(page2.getId() + "/likes", Likes.class, Parameter.with("fields", "data"));`

The following is the output:

`FINE: Facebook responded with HTTP status code 200 and response body: {"data":[{"id":"376948372507251"},{"id":"241248055929173"},{"id":"375977992570452"}],"paging":{"cursors":{"before":"Mzc2OTQ4MzcyNTA3MjUx","after":"MTM4NDI3MDQ5NTI0NjQ5"}}}

Likes: Likes[canLike=null data=[] hasLiked=null totalCount=0]
Likes: Likes[canLike=null data=[] hasLiked=null totalCount=0]
Likes: Likes[canLike=null data=[] hasLiked=null totalCount=0]`

What should i do so that the Likes class gets populated with the data array

**Comment by rgupta77** [comment]
Hi Norbert, When i use the following query 
https://graph.facebook.com/v2.8/1347629308665541/feed?limit=100&access_token=146055952628403%7CZLntKASz1sjS1y8ZLKVFnfFRE400&format=json
I get 0 posts from graph api, I am using the _application Token_ to get the posts from a particular user.

1347629308665541 is a facebook users UserId which i have fetched by getting the users who like a particular facebook POST.

Is it possible to get posts made by a user using the application token, by using the UserId? since I am running a windows service (which gets posts using restFB) and hence i wont be able to get the User access token without UI login.

Please let me know.
