### ISSUE TITLE
FacebookGraphException occurred when iterating Insights

### ISSUE THREAD

**Issue by limarsol** [restfb/restfb#1265]
FacebookGraphException occurred when iterating Insights on some of the Facebook Pages I maintain. 

The data can be successfully pulled from Facebook Server using the library but during iteration of insights data, FacebookGraphException is thrown.

Observed the issue from version 2022.7.0 and beyond. Thanks!

**Comment by nbartels** [comment]
Can you please post the stacktrace and the json of the insights here.

**Comment by limarsol** [comment]
Hello kindly see logs attached
[debug_logs.log](https://github.com/restfb/restfb/files/10371801/debug_logs.log)

**Comment by limarsol** [comment]
In addition, the insights are iterated 3 times

**Comment by limarsol** [comment]
Sorry I meant to say duplicated 3 times

**Comment by nbartels** [comment]
It looks like the URL for the "next" page is somhow not working. Can you check if there is a difference between the next URL from the JSON and the actually called URL that you find in the log?

**Comment by limarsol** [comment]
Sure! Will check on it and get back to you as soon as possible. thanks!

**Comment by limarsol** [comment]
Hello @nbartels,
I have compared the provided next page URL by Facebook and the actual next page URL called. Both matched and does not have any difference.

**Comment by nbartels** [comment]
This means, that the URL cannot be called for some reason on Facebook and at this time I suggest you try to use the Graph Api Explorer (https://developers.facebook.com/tools/explorer/) and go there through your workflow. Unsupported GET requests mean that there is something wrong with the URL or your permissions. Because you use the returned URL from Facebook, it does not look like RestFB changed the url.

If you can also reproduce the problem in the Graph Api Explor the next step would open a bug at Facebook.

**Comment by limarsol** [comment]
Hello @nbartels , Thanks for the response! Yes I have checked in Graph API explorer as well and the next page URL provided by Facebook returns the error. Will open a bug at Facebook. Thanks!
