### ISSUE TITLE
Custom Open Graph Support

### ISSUE THREAD

**Issue by debbas** [restfb/restfb#163]
Hey Guys,

I would like to publish a story that has an open graph. I know how to publish with a url. However is there a way to create the object and publish it.

Thanks,
Ramez

**Comment by nbartels** [comment]
Because the custom open graph stories are ... hm ... custom, I don't think we can provide some support. You may create a JSONObject and post it to facebook as they show in the documenation (https://developers.facebook.com/docs/sharing/opengraph/object-api).

If there are better ideas how we can support that issue, I really like to hear them ... otherwise I would close this issue soon.
