### ISSUE TITLE
comments can be paged

### ISSUE THREAD

**Issue by sjpotter** [restfb/restfb#17]
as per demo url given out by fb in regards to notes

https://graph.facebook.com/122788341354?access_token=AAAAAAITEghMBAKIVxJBsorHcuNiq9Opbq4joOtgUPUIl6TLBvspbAUCgZBYwVGmYzCl9AL0AHpOrbuuCPE0ga6sIdISGawQt9uhbjFAZDZD

it appears that comments can have paging, not an issue I've hit, but doesn't seem like api takes it into account.

**Comment by frapontillo** [comment]
Any update on this?

**Comment by samuraiu** [comment]
I have one other issue, when you retreive a connection and u have Comments, you may go through comments with iteration, but each comment may have list of comments as well, and you get them only 25, which is the limit, what if there are 50 comments, how do you iterate with paging over those sub comments ?

**Comment by nbartels** [comment]
you can make a call to ```<commentid>/comments``` and access all the comments. I'm not sure what is Facebook's intention with the iteration over the comments of some object. Perhaps it's only some kind of preview if you fetch a comment/album/post or whatever, to show some comments and the whole list should be retrieved in a different way. 

But I think these comments you mention have a cursor (after/before) available and so you could use that. Currently we don't support cursors in that way. In fact we have already an issue regarding the cursors (Issue #191 ).

**Comment by samuraiu** [comment]
Yes that is what i am doing, i make a batch request for post_id/comments, make a connection from it, then i iterate through it, and for each comment i check if they have a sub_comments count, and if they do, i make another connection with comment_id/comments so i get their subcomments.. I just think its silly if you can already get subcomments of comments with post_id/comments - fields(id,comments), but u cant get them more then 25 because of limitation, so you cant get them with one go.

**Comment by samuraiu** [comment]
And about cursors, subcomments of comments receive paging next if there are more then 25, so when you create connection you can iterate through them
