### ISSUE TITLE
Using the DefaultJsonMapper causes an issue in Groovy

### ISSUE THREAD

**Issue by monksy** [restfb/restfb#268]
I'm getting the issue when using a true GString (GStringImpl) class on sending in a string to a parameter. The serialized output of the GString is {}. It should be the full string. 

For example: The GString "${Date.now}" would result in "%7D%7B" rather than the actual contents.

At the moment the only workaround is to use the toString on the GString coming in.

**Comment by slumx** [comment]
This can only be a groovy issue. Restfb is written purely in java and cannot affect how groovy evaluates GStrings

**Comment by nbartels** [comment]
Not really. It's a bit more complicated. You try to use your `GString` as Parameter value.

So the JsonMapper tries to convert the object. `GString` extends `Object` and none of the normal checks work. It''s not a `Map`, `List` or some primitive. So the Mapper assumes the `GString` to be a RestFB type. Now it searchs for fields with the `Facebook` annotation, but obviously it has no annotation. So the mapper decides to return a empty object and convert that to json. That's why you get `{}`.

Now, to the solution. It makes no sense to add a special mapping for GStrings. Three ways are possible. You use `toString` (your workaround), you write your own `jsonMapper` (perhaps a bit overkill for this problem) or I add a fallback if a object is detected and it has no Facebook annotated fields. The fallback would call toString, but I think that could result in some problems.

Anyway interesting problem.

**Comment by slumx** [comment]
Sorry for my reply then. I forgot that the parameter value is of type Object (which makes sense) and not String. If the type was String groovy would automatically invoke toString() on GString to convert to String and thereby resolving the GString placeholders

**Comment by slumx** [comment]
Maybe an exception would be right for this issue when restfb cannot find any suitable way of parsing the input parameter?

**Comment by monksy** [comment]
@nbartels You explained that a lot better than I did. It might be a bit better to use Jackson to do the conversion there. That's a bit more compatable for converting back and forth with JSON.

**Comment by nbartels** [comment]
@monksy Can you please convert the GString with jackson into a json string? I'd like to see what they create. 

If they look into the object and use the inner fields, the created JSON may not what you expect :smile:

**Comment by nbartels** [comment]
So I checked your suggestion and  - as I thought - it makes no difference.

```java
GString gs = new GStringImpl(new Object[]{new Integer(123)},new String[]{""});
ObjectMapper mapper = new ObjectMapper();

System.out.println(mapper.writeValueAsString(gs));
``` 

The output is ```{"strings":[""],"bytes":"MTIz","values":[123],"valueCount":1}``` and not what you expect when calling a `toString` and map the String afterwards.

So RestFB provides not a generic way to convert any Object to a json, but uses the annotations. In my opinion everything works correct and as expected.
