### ISSUE TITLE
Email shows null

### ISSUE THREAD

**Issue by akhilesht** [restfb/restfb#374]
I am trying to retrieve emails of users from a group. I am able to retrieve name and id but the email is coming as null for all the users. I have also included email as field in the parameters. What am I missing?

```java
user = delegate.facebookClient.fetchObject(user.getId(),User.class,
						Parameter.with("fields", "id,name,email"));
System.out.print(user.getName());  /this is displayed
System.out.print(" "+user.getEmail()); // this is coming as null all the time.
```

**Comment by nbartels** [comment]
The `email` field is only filled if the user made his email address publicly available. You should see the email on the user profile if the user is not a friends of yours.

At least that's my interpretation of the Facebook Graph API Reference regarding the email field on users. And after checking some users it seams to be true :smile: 

> The person's primary email address listed on their profile. This field will not be returned if no valid email address is available

I think Facebook don't provide a easy access to the email address because spammer could fetch lots of addresses. And no one likes to get spam.
