### ISSUE TITLE
Checked vs. unchecked exceptions

### ISSUE THREAD

**Issue by hkroger** [restfb/restfb#477]
Hi,

Ran into this in the docs: "All FacebookClient methods may throw FacebookException, which is an unchecked exception as of RestFB 1.6.".

In the Oracle docs the main guideline says: "Here's the bottom line guideline: If a client can reasonably be expected to recover from an exception, make it a checked exception. If a client cannot do anything to recover from the exception, make it an unchecked exception." 

(See: https://docs.oracle.com/javase/tutorial/essential/exceptions/runtime.html)

We need to handle all the exceptions which the library might throw and using runtime exceptions makes that harder. So, why unchecked exceptions?

**Comment by revetkn** [comment]
Ha, this was a point of contention 5 years ago (and probably will be 5 years from now too) 😄 

You can search the RestFB google group for all the gory details, here is one starting point: https://groups.google.com/forum/#!searchin/restfb/unchecked/restfb/wwPtwaEy6CM/Sapk6-Rr_OkJ  I deliberately picked checked exceptions when RestFB started and was later convinced to go the unchecked route.  Here are some of my thoughts from 2011 about changing to unchecked:

> FacebookException was a checked exception precisely because it was
> sometimes recoverable (bad access token, network acting weird, etc.)

> But I do tend to dislike checked exceptions, and Jeff's arguments are
> pretty good, which is why I ended up making the change.  And, in
> practice and having worked on a lot of apps, I think having to write
> throws clauses all over the place and rethrowing checked exceptions
> yourself ends up adding a lot of clutter and doing more harm than
> good.  So I think we'll probably stick with unchecked exceptions. I
> have tried to make the javadoc explicit about what exceptions are
> thrown even though they're unchecked - I hope that much is helpful, at
> least.

You can go from checked to unchecked without breaking any code at compile time, but "putting the genie back in the bottle" now by moving from unchecked to checked will cause problems and would have to be part of a breaking 2.x release.

I would say that @nbartels' opinions on this are the most important since he's running the show.

**Comment by nbartels** [comment]
That's an interesting topic and I checked a bit what's state of the art. 

It seems that checked exceptions are not used anymore in the way they were used at the beginning of Java. Spring for example throws only `RuntimeExceptions`.

@hkroger perhaps you can explain why it is hard to catch runtime exceptions. You may, for example, just catch the `FacebookExceptions` and you are done. Almost all exceptions RestFB throws are big problems for the software that's built upon and it is unlikely that RestFB will recover itself. 

RestFB uses checked exception in the device token area, because here an exception is rather normal and we expect the user to handle this. But in the normal workflow, the software component is "dead" as soon as Facebook throws an error (and we built an exception) or a JSON is unparseable.

But perhaps we can talk about this further and learn more about current java development. :smile:

**Comment by cowwoc** [comment]
See http://stackoverflow.com/a/19061110/14731 for an extensive answer of when you should use checked vs unchecked exceptions.

**Comment by hkroger** [comment]
Well, I guess this is a big religious debate that we can go into if we really want it. My personal preference here just would have been to have some sort of code level check for the exception handling. I know there are different sorts of exceptions that can be handled on application level. 

If you see here:
https://developers.facebook.com/docs/graph-api/using-graph-api#errors

There are lots of exception cases which could be retried if there is an error. So if checking the check list in a link provided by @cowwoc it fulfills the "Expected but unpreventable" and "Reasonable to recover from" requirements.

That being said I can live with the current interface definition as well and just try to catch all exceptions.
