### ISSUE TITLE
How to determine the Webhook type?

### ISSUE THREAD

**Issue by marceloverdijk** [restfb/restfb#545]
What is the recommended way to retrieve the webhook type (`message`|`postback`|`..`) from the `MessagingItem`?

In the docs I read:

> The value-field of the Change object is very interesting. Here we added a new solution and made use of the @JsonMappingCompleted annotation in combination with a ChangeValueFactory.

> Beacuse the difference between the WebhookObjects you receive from Facebook lies in the change value, we implemented a factory **so you can work with the correct entity and don’t need to implement some logic**.

(ps there is a typo in the docs: `Beacuse`)

But I don't understand how to do it **without the need to implement logic** (as mentioned in the second paragraph).
What I'm basically doing now is:

    for (WebhookEntry webhookEntry : webhookObject.getEntryList()) {

        for (MessagingItem messagingItem : webhookEntry.getMessaging()) {

            if (messagingItem.getMessage() != null) {
                 // handle message
            } else if (messagingItem.getPostback() != null) {
                // handle postback
            } ..

Is this the correct way to determine the webhook type?

I also noticed the `Change` field is registered at `WebhookEntry` level but not on `MessagingItem` level.

Any feedback is appreciated.

**Comment by nbartels** [comment]
Yes, the section in the documentation talks about the non message bot webhooks. The messaging object needs a if-then-else. We can think about changing this, but at the moment this structure is defined by Facebook and we follow that definition. 

Thanks for the typo ;)

**Comment by marceloverdijk** [comment]
No problem @nbartels to use the `if-then-else` for the webhooks.
Would you be able to give a short example ow to handle the non message bot webhooks. For me it's not clear yet how to handle the list `Change` fields on the `WebhookEntry` instance, how it's exact purpose is.

Btw I'm thinking of writing a small (open source) library that makes it easier to implement a facebook bot. Of course it will heavily depend on restfb as restfb has the whole infrastructure to receive and send messages already :-)
However what the library will provide is a out-of-the-box Webhook servlet and utility classes that make it easier to send back a message to the client.

E.g. instead of: 

    SendResponse sendResponse = facebookClient.publish("me/messages", SendResponse.class,
        Parameter.with("recipient", recipient), // the id or phone recipient
        Parameter.with("message", message)); // one of the messages from above

one could just do:

    SendResponse sendResponse = messenger.sendTextMessage(recipient, message));

And I'm also thinking of providing a event handler system to receive webhooks, then there would be no need to for the `if-else-then`.

Anyway it will be a small library but I wonder is there recommended naming convention for restfb extensions? I could for example use something like `restfb-chatbot`.

**Comment by nbartels** [comment]
Okay, so the WebhookEntry is not Chatbot centered. So this is a generic way to handle incoming Webhook requests. If you subscribe to other page fields (e.g. `feed`) the changes are filled, because Facebook sends these changes in batches. You can get up to 1000 changes in a webhook request. 

Chatbots use the same entry point but use different fields. Therefore the changes make in a chatbot not that much sense. But this would be something you may handle in your library. Btw, have a look at our test cases for the webhook types. There you see a lot of example json you can receive from Facebook and then you get how the WebhookObject, Entry and the changes work. And of course, the Chatbot requests.

We discuss your high-level API internally and tell you how the convention is and how we can support you.

**Comment by marceloverdijk** [comment]
Thanks a lot @nbartels

**Comment by marceloverdijk** [comment]
Note that besides providing a fully working servlet, I also want to provide a Spring Boot starter to help Spring Boot users to quickly use the library (and it's restfb dependency).

**Comment by nbartels** [comment]
Okay, so you may build your library and use the restfb name in it. Your suggestion is good because the examples project is named restfb-examples :) So you can name it restfb-chatbot.

I have some additional comment to the `if-then-else` using the `MessagingItem`. You can simply call `getItem` and check the type (with `instanceof`) afterwards. Perhaps you like that more and it's a bit clearer what's happening. Check this: https://github.com/restfb/restfb/blob/master/source/library/com/restfb/types/webhook/messaging/MessagingItem.java#L84

**Comment by marceloverdijk** [comment]
Thanks for feedback @nbartels, I will keep you updated!
