### ISSUE TITLE
What version of Facebook Graph API can restfb 1.6.16_release support

### ISSUE THREAD

**Issue by TohsakaRIN** [restfb/restfb#563]
Hi Guys,

The restfb our product used version is 1.6.16_release. 
At the same time the Facebook application we created used Graph API 2.0, which will reach the end of the 2-year deprecation window on Monday, August 8, 2016. 
So we need migrate all calls to v2.1 or higher in order to avoid potential broken experiences.

I inquire about the historical version of the restfb and Facebook Graph API relationship, or did not find what is the newest version of Facebook Graph API restfb1.6.16 support.

Can you help me to answer it?If I apply for a new Facebook application with Facebook Graph API 2.5 version, do I need to upgrade restfb?

Thanks!

**Comment by nbartels** [comment]
If I understand you right you like to get a Graph API/RestFB Version mapping? The fastest way is to have a look at the changelog. Because as soon as a new version is released by Facebook we change the Version enum in RestFB and in general we have every issue listed in the changelog. And no code change is done without issue.

But you can simply try the newest version. We support the latest Graph API version and try to still have a compatibility down to the oldest version that is in wild. So 1.30.0 supports Graph API 2.1, too.
