### ISSUE TITLE
Convenience methods for fetching all available data

### ISSUE THREAD

**Issue by jamesblau** [restfb/restfb#628]
This is more of a question than a bug (hope that's OK, per the homepage).

Is there a convenient way to get all available data for a Facebook page? I've been asked to collect everything relating to a page (to which I have permissions) with photos, videos, posts, likes, likes on posts, etc. (I've just been collecting raw json.) I was hoping to be able to say something like:

`(new DefaultFacebookClient(pageToken)).getAll.map(getAll)`

But instead I find myself writing loops to specify each thing I want and then page through them.

Is there a way to avoid writing lots of specific paging loops, or an example of someone efficiently using restfb to do something like this? Would "convenience methods" for slurping in all available data be useful for restfb, or does the API change too rapidly for this to be plausible?

Thanks for the help, and sorry if this is answered (or should be asked) elsewhere!

**Comment by nbartels** [comment]
RestFB is in the first place a low level library. We try make the communication with the Facebook APIs more easy and developer friendly. 

In an experimental package, we added some convenience methods to solve simple and often used tasks, but they are not used as expected. The developers implement their custom solutions and with some changes Facebook made it is even more complicated to support all possible ways a developer is using the API so it's up to the devs to write things like a `getAll`. 
The fields need to be configurable and because "all" contains very different types of objects, the fields need to be configured for all of them. Posts, Conversations, Comments are all different. 
Additionally the error handling should be very clever and you'll run definitely into some rate limits. 

So we cannot provide you what you request but feel free to implement another library on top of RestFB. @marceloverdijk did this for the Chatbots and we support these implementations as far as they don't disturb the "normal" use cases.

**Comment by jamesblau** [comment]
Fair enough; that's what I'd feared. I would have imagined that enough people would want this functionality that it would be worth implementing once in restfb rather than multiple times by individual devs, but I guess not.

Thanks for the prompt response, anyway! I will take a look at marceloverdijk's.

**Comment by nbartels** [comment]
I think every developer has a special use case and needs special fields and object. So the overhead that would be introduced by adding a good way to configure the `getAll` for all these use cases is too big. And with the current implementation a developer has a good insight and control over the Graph API. She can simply check the Graph API Explorer and transfer the call almost 1:1 to RestFB.

But I admit that the Graph API may be confusing especially for "beginners".

**Comment by marceloverdijk** [comment]
@nbartels it might be interesting to add a section on docs/github with libraries using restfb?

**Comment by nbartels** [comment]
@marceloverdijk sure, but it is a very short list atm 😄 . Please send me a description, link and name and I'll add it to github and in our documentation.
