### ISSUE TITLE
Can't use Version 2.9 in latest RC

### ISSUE THREAD

**Issue by lostpebble** [restfb/restfb#754]
As per title, I'm using the latest 2.0.0-rc.2 but I can't access the constant for Graph API V2.9 when creating my client.

**Comment by nbartels** [comment]
That's because I should publish a rc3. In the dev-2.0 branch this changes are already made, but not published as release candidate for the 2.0 release. The latest 1.43.0 has the latest version already. So you have several possibilities. 
1. use 1.43.0
2. build a 2.0 snapshot from latest source
3. wait for rc3 (I try to publish it soon)

Sorry for the inconvenience

**Comment by lostpebble** [comment]
No worries, V2.8 seems to be doing the trick for me at the moment.

I'll be waiting for RC3. Unfortunately for the time being I'm using the "timezone" property on the Event entity, which isn't available in 1.43.0 from what I can see.

**Comment by nbartels** [comment]
The RC3 should be available on Maven central soon...
