### ISSUE TITLE
ChangeValueFactory tries to convert a string to JsonObject and throws exception

### ISSUE THREAD

**Issue by maurocanuto** [restfb/restfb#785]
In ChangeValueFactory, setValue method returns an Error when receiving a Webhook for type User with INCLUDE VALUES Option on.

```
public ChangeValueFactory setValue(String var1) {
        this.value = new JsonObject(var1);
        return this;
    }
```
The value sent by Facebook is not a json value and new JsonObject(var1) throws an exception.

*How to reproduce*
Send a User webhook with include values on (E.g. changing email).
Payload received is:

`{"entry": [{"time": 1505485762, "changes": [{"field": "email", "value": "example_email@facebook.com"}], "id": "0", "uid": "0"}], "object": "user"}`

Error thrown is:
`com.restfb.json.JsonException: A JsonObject text must begin with '{' at character 1`

**Comment by nbartels** [comment]
I checked the INCLUDE VALUES option and your problem is only one of some more. The value can be a String (your case) a JsonObject (the current default) or an JsonArray (unhandled atm, see `work_history` for an example).

So we have to find a solution that suits these 3 cases and does not break the current implementation (too much). 

Many thanks for this hint!
