### ISSUE TITLE
How to avoid exceeding rate limit

### ISSUE THREAD

**Issue by mahmoudhanafy** [restfb/restfb#792]
I have a question about rate limit. 
I can't find any documentation here about it and want to know if it is being handled automatically?
or is there any useful information I can get and will let me avoid exceeding the limits!

**Comment by nbartels** [comment]
You can simply check the debug header information Facebook provides. You can find this information in our documentation: http://restfb.com/documentation/#error-ratelimiting

More documentation regarding rate limiting: https://developers.facebook.com/docs/graph-api/advanced/rate-limiting/

And my personal opinion is to use as less calls as possible. Use everything the API already provides and don't make unnecessary calls. In an application I work on, we managed to reduce the calls by 70% with this approach.

**Comment by mahmoudhanafy** [comment]
Thank you for your response. I have another question:
What should I do when I found that I'm approaching limits?
for ex. when fetching data from Twitter, Twitter return the next date the limits will be available again, So I sleep until this date.
What should I do in Facebook case?

**Comment by nbartels** [comment]
You have to monitor your requests and reduce the amount of them. Additionally you can use some "reducing" techniques, like rework the calls, cache some information and of course let the user (if some calls depend on user interaction) only fetch a defined amount in a time slot.

You can increase the time between fetches.

For example: We fetch posts and the comments that belong to that post. So we make first a call to fetch a post and include the comments summary in the post. So we are able to decide if it is necessary to make a "fetch comments" call. Posts without comments don't need this calls. So I can save 1 call for Posts without comments. Not much, but depending on the use case very useful. 

Then we use webhooks to get notified about new posts and comment so we don't need to crawl to complete feed and only fetch new information. User profile information are cached for a short time period. The user profile is only loaded once per 1 hour. Because we only use name and profile picture.
