### ISSUE TITLE
Get limited feed

### ISSUE THREAD

**Issue by joelforessottile** [restfb/restfb#842]
**How can I get a limited feed?** This is what I've tried and all the posts are being printed out instead of the last five.
`PostWithDetailedReactions post = fbClient.fetchObject(this.postTest,
PostWithDetailedReactions.class,
Parameter.with("fields", fields),
Parameter.with("limit",5));`
I know that another way to get last posts is using the timestamp, which I already tried and it worked. But I'd like to know how to limit the amount of feed that I'm getting for further ideas that I'd like to implement. Plus, I only want to show a certain amount of the lasts pots, not just the last ones since a date.

**Comment by nbartels** [comment]
First of all, `limit` is not the overall limit. It is the amount of elements per page. 

You can solve the problem like explained in this comment: 
https://github.com/restfb/restfb/issues/232#issuecomment-101299950

**Comment by joelforessottile** [comment]
@nbartels woah I feel so dumb now haha I'll check it out. Thanks

**Comment by nbartels** [comment]
Just a short note: If you only need some posts from a feed and these are all on the first page you can take the example from the comment above and instead of using the loop construction call `feed.getData()`. Then you get the list of posts on the page the connection points to. Normally the first page ;)

**Comment by joelforessottile** [comment]
@nbartels Thanks!
