### ISSUE TITLE
Request for support of Facebook Instagram API

### ISSUE THREAD

**Issue by martinmalek** [restfb/restfb#851]
Wondering if you have considered including support for Facebook Instagram APIs?

- https://developers.facebook.com/docs/instagram-api
- https://developers.facebook.com/blog/post/2017/08/31/instagram-api/
- https://developers.facebook.com/products/instagram/

**Comment by nbartels** [comment]
Hm, sounds interesting and I already realized that there are some instagram specific permissions. 
We have to check the API a bit more and check if we can get all necessary information . In that case we really like to support that API.

**Comment by martinmalek** [comment]
Since it's graph api I'm assuming a few new endpoints, POJOs and as you said permissions. 

Apart from me greatly simplifying the efforts, would you be able to provide a rough estimate of the effort and timeframe it would require?

**Comment by nbartels** [comment]
Yes, you're right, but sadly I have no example json. If you can provide some obfuscated ones it would be great. Otherwise I have to use the information from the FB documentation. 

I'd like to split this into 2 tasks. First adding the permissions (Release 2.2.0) and adding the Pojos (Release 2.3.0). So it should faster be possible to use instagram. 2.2.0 should be released soon, 2.3.0 afterwards, but everyone can take the pojos source from the github repo.

**Comment by nbartels** [comment]
As you can see, 2.2.0 is released and we are working on the 2.3.0 with instagram support. I close this issue and you can monitor the progress in our issue list.
