### ISSUE TITLE
Format message reply to user is  JSON ???

### ISSUE THREAD

**Issue by apovn** [restfb/restfb#866]
I'm making an FB App and using restfb to send message to user.

First, I get thread_id in conversation of Page like this: t_1008785457
Second, I use restfb to reply message to user like below:

![image](https://user-images.githubusercontent.com/15623657/37763326-4a1d060c-2df1-11e8-82cd-b4b9257b1e12.png)

Third, I open FB Page Inbox and see:
![image](https://user-images.githubusercontent.com/15623657/37763107-bf225fc0-2df0-11e8-9adf-5bc640a475fb.png)

It should be the text only: **"Just a simple text"**, not all JSON format object.

Is anyone get this error before ?

**Comment by nbartels** [comment]
There is a difference between private messages and private messages ;)

It depends on the platform you are using. It seems you try to add a new message to a conversation. That's why there is a `thread_id` in the publish path. So your are using the normal way to interact between a page and a user. Here you have to use a simple String for the message.

The second way is the messenger platform, bots are talking to users in a different way. They use another endpoint (without `thread_id`) but the similar parameters. The `Message` object you use, is for the bots. Additionally you don't have set the recipient, so I think you don't intend to use the Messenger Platform

That's the reason this is not working. 

Replace `Message` by `String` and everything's fine.

**Comment by apovn** [comment]
Thank @nbartels , I use String and it worked well 👍 . 
About the second way. Is that the way we use: create Bots, create Page, setup webhook. And everytime users send message to Page, Bots will receive and reply follow what you implement ? Is that the most common way now or have some other ways ?

Thanks

**Comment by nbartels** [comment]
Great it is working now.

It depends on the scope of your application. As long as you provide an interface to "humans" for responding to incoming private messages you are on the right track.

If you like to automatically respond to messages and do some stuff without a human interaction, than you can go the Messenger Platform way. RestFB supports this, but you can also use https://github.com/marsbits/restfbmessenger (a library that encapsulates our low level operations and is based on RestFB).

**Comment by apovn** [comment]
Thank you, I will check the link. I updated the question above.

Is there a way to interact between user and user (without FB page) ?
Ex: you create a FB app like a Bot, you will have user_access_token. This FB app will represent the owner of FB account. This account have some friends and you use the token in code and send message to friends. Is this scenario above valid ? Or can I send messages to my friends without creating FB Page ?

Do you have experience about this case ? Is this valid ?

**Comment by nbartels** [comment]
No, sending messages to users is triggered by the user. 
In every case, bot or not, the user has to send a message (only exception is a comment on a page post which can be interpreted as message) to allow a page send messages to the user.

**Comment by apovn** [comment]
Okie. I understand. Thank you for your answer.
