### ISSUE TITLE
Deserialisation issue with JsonNumber

### ISSUE THREAD

**Issue by ErfanMaybe** [restfb/restfb#870]
Hi guys!

Thanks for a great and useful API, we've been using it for years and can't be happier with it.  

Recently we've updated from 1.42.0 to 2.3.0. We're now seeing some issues on deserialisation when caching `User` object to redis. We usually cache user objects to minimise unnecessary Facebook API calls and not go over the the limitation. In 1.42.0 we have no issues whatsoever but when caching the user object in 2.3.0 we get issues on deserialisation `JsonNumber`. Here's a stacktrace of the exception thrown:  

```
com.fasterxml.jackson.databind.exc.InvalidDefinitionException: Cannot construct instance of `com.restfb.json.JsonNumber` (no Creators, like default construct, exist): cannot deserialize from Object value (no delegate- or property-based Creator)
 at [Source: (io.netty.buffer.ByteBufInputStream); line: 1, column: 1524] (through reference chain: com.restfb.types.User["rawPicture"]->com.restfb.json.JsonObject["values"]->java.util.ArrayList[0]->com.restfb.json.JsonObject["values"]->java.util.ArrayList[0])
   at com.fasterxml.jackson.databind.exc.InvalidDefinitionException.from(InvalidDefinitionException.java:67) ~[jackson-databind-2.9.3.jar:2.9.3]
   at com.fasterxml.jackson.databind.DeserializationContext.reportBadDefinition(DeserializationContext.java:1451) ~[jackson-databind-2.9.3.jar:2.9.3]
...
```

Here's the minified obfuscated JSON being deserialised:  

```
{"@class":"com.restfb.types.User","birthday":"01/01/1970","devices":["java.util.ArrayList",[]],"education":["java.util.ArrayList",[]],"email":"john.doe@gmail.com","favoriteAthletes":["java.util.ArrayList",[]],"favoriteTeams":["java.util.ArrayList",[]],"firstName":"John","gender":"male","id":"1234567890","idsForApps":["java.util.ArrayList",[]],"idsForBusiness":["java.util.ArrayList",[]],"idsForPages":["java.util.ArrayList",[]],"inspirationalPeople":["java.util.ArrayList",[]],"interestedIn":["java.util.ArrayList",[]],"invitableFriends":["java.util.ArrayList",[]],"labels":["java.util.ArrayList",[]],"languages":["java.util.ArrayList",[]],"lastName":"Doe","meetingFor":["java.util.ArrayList",[]],"picture":{"@class":"com.restfb.types.ProfilePictureSource","height":497,"isSilhouette":false,"url":"https://lookaside.facebook.com/platform/profilepic/?xxx","width":497},"rawPicture":{"@class":"com.restfb.json.JsonObject","array":false,"boolean":false,"empty":false,"false":false,"names":["java.util.ArrayList",["data"]],"null":false,"number":false,"object":true,"string":false,"true":false,"values":["java.util.ArrayList",[{"@class":"com.restfb.json.JsonObject","array":false,"boolean":false,"empty":false,"false":false,"names":["java.util.ArrayList",["height","is_silhouette","url","width"]],"null":false,"number":false,"object":true,"string":false,"true":false,"values":["java.util.ArrayList",[{"@class":"com.restfb.json.JsonNumber","array":false,"boolean":false,"false":false,"null":false,"number":true,"object":false,"string":false,"true":false},{"@class":"com.restfb.json.JsonLiteral","array":false,"boolean":true,"false":true,"isFalse":true,"isNull":false,"isTrue":false,"null":false,"number":false,"object":false,"string":false,"true":false,"value":"false"},{"@class":"com.restfb.json.JsonString","array":false,"boolean":false,"false":false,"null":false,"number":false,"object":false,"string":true,"true":false},{"@class":"com.restfb.json.JsonNumber","array":false,"boolean":false,"false":false,"null":false,"number":true,"object":false,"string":false,"true":false}]]}]]},"sports":["java.util.ArrayList",[]],"work":["java.util.ArrayList",[]]}
```

**Comment by nbartels** [comment]
Thanks!

So I think there are two problems. First of all the `rawPicture` field should be transient, because it makes not that much sense to double the values especially if these serialized fields are not accessible anymore.

On the other hand, the JSON objects should be serializable. I think we should add default constructors for them. I have to check first how "your" the serializing mechanism is working.

**Comment by nbartels** [comment]
Okay, I think I found a solution that is minimal and solves your problem. The `rawPicture` is a `String` now. This should be no problem for other users, but on serialisation there is no `JsonObject` and therefore no `JsonNumber` as part of it.

**Comment by ErfanMaybe** [comment]
Thanks @nbartels 👍. Any reason on why default constructor was not a good solution? Just curious!

**Comment by nbartels** [comment]
I tried your use case and wrote a short unit test to check the de/serialisation of a java object to JSON and vice versa with jackson. First it looked promising, but the `JsonNumber`, `JsonString` and `JsonLiteral` contain a private final field and it was not enough to add the constructor without parameter. With that change it was not possible to serialise the complete object to JSON. The final field was missing and so it was not possible to deserialise the JSON to the former object. 

Because the json implementation is directly taken from `minimal-json`, we don't want to make big changes on our copy. But I can open up a issue there, so we can take a upcoming `minimal-json` release into a later release.

Hope this explains the decision 😃

**Comment by nbartels** [comment]
I link the minimal-json issue, too: 
https://github.com/ralfstx/minimal-json/issues/92
