### ISSUE TITLE
Post private message from a page with text AND attachment

### ISSUE THREAD

**Issue by bartw** [restfb/restfb#903]
Hello,

Is it possible to post a private message with text and an attachment using restfb?

Thanks

**Comment by nbartels** [comment]
No, text and attachment is not possible, because Facebook requires a message to contain text or attachment. (https://developers.facebook.com/docs/messenger-platform/reference/send-api#payload) Furthermore you can only send attachments with the Send API (Chatbot). With the Pages API it is even not possible to send an attachment at all (if nothing changed lately).

**Comment by bartw** [comment]
Thanks for the quick reply.
As a work-around I now post 2 messages, first the attachment and then the text.
